services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - BUILD_TYPE=musl
    volumes:
      - .:/source:z
      - ./data:/app/data:z
    command: server
    environment:
      - RUST_LOG=debug
    ports:
      - "8080:8080"
